# Site settings
title: Resume
description: Resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: N.Vikram Raj
user_description: I'm a student from B.S Abdur Rahman Crescent Institute of Science and Technology currently pursuing ECE.
user_title: 
email: nvikramraj1305@gmail.com
twitter_username: random_guy_1o1
github_username: nvikramraj
gplus_username: nvikramraj

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
